import { ProjectPermission, PROJECT_PERMISSION } from "./projectPermission.js";

import { ProjectRole, PROJECT_ROLE } from "./projectRole.js";

export const PROJECT_ROLE_PERMISSIONS: Record<
  ProjectRole,
  ProjectPermission[]
> = {
  [PROJECT_ROLE.ADMIN]: [
    PROJECT_PERMISSION.MEMBER_ADD,
    PROJECT_PERMISSION.MEMBER_READ,
    PROJECT_PERMISSION.MEMBER_UPDATE_ROLE,
    PROJECT_PERMISSION.MEMBER_REMOVE,

    PROJECT_PERMISSION.TASK_CREATE,
    PROJECT_PERMISSION.TASK_READ,
    PROJECT_PERMISSION.TASK_UPDATE,
    PROJECT_PERMISSION.TASK_DELETE,
    PROJECT_PERMISSION.TASK_ASSIGN,
    PROJECT_PERMISSION.TASK_CHANGE_STATUS,
    PROJECT_PERMISSION.TASK_CHANGE_PRIORITY,

    PROJECT_PERMISSION.COMMENT_CREATE,
    PROJECT_PERMISSION.COMMENT_UPDATE,
    PROJECT_PERMISSION.COMMENT_DELETE,

    PROJECT_PERMISSION.ATTACHMENT_UPLOAD,
    PROJECT_PERMISSION.ATTACHMENT_DELETE,

    PROJECT_PERMISSION.ACTIVITY_READ,

    PROJECT_PERMISSION.DOCUMENT_CREATE,
    PROJECT_PERMISSION.DOCUMENT_READ,
    PROJECT_PERMISSION.DOCUMENT_UPDATE,
    PROJECT_PERMISSION.DOCUMENT_DELETE,

    PROJECT_PERMISSION.FILE_READ,
    PROJECT_PERMISSION.FILE_UPLOAD,
    PROJECT_PERMISSION.FILE_DELETE,
  ],

  [PROJECT_ROLE.MEMBER]: [
    PROJECT_PERMISSION.MEMBER_READ,

    PROJECT_PERMISSION.TASK_CREATE,
    PROJECT_PERMISSION.TASK_READ,
    PROJECT_PERMISSION.TASK_UPDATE,
    PROJECT_PERMISSION.TASK_CHANGE_STATUS,
    PROJECT_PERMISSION.TASK_CHANGE_PRIORITY,

    PROJECT_PERMISSION.COMMENT_CREATE,
    PROJECT_PERMISSION.COMMENT_UPDATE,

    PROJECT_PERMISSION.ATTACHMENT_UPLOAD,

    PROJECT_PERMISSION.ACTIVITY_READ,

    PROJECT_PERMISSION.DOCUMENT_READ,
    PROJECT_PERMISSION.DOCUMENT_CREATE,
    PROJECT_PERMISSION.DOCUMENT_UPDATE,

    PROJECT_PERMISSION.FILE_READ,
    PROJECT_PERMISSION.FILE_UPLOAD,
  ],

  [PROJECT_ROLE.VIEWER]: [
    PROJECT_PERMISSION.MEMBER_READ,

    PROJECT_PERMISSION.TASK_READ,

    PROJECT_PERMISSION.ACTIVITY_READ,

    PROJECT_PERMISSION.DOCUMENT_READ,

    PROJECT_PERMISSION.FILE_READ,
  ],
};
