
import { Permission, PERMISSION, PERMISSIONS } from "./permission.js";
import { Role, ROLE } from "./roles.js";

export const ROLE_PERMISSIONS : Record<Role,Permission[]> = {
  [ROLE.OWNER]: PERMISSIONS,

  [ROLE.ADMIN]: [
    PERMISSION.WORKSPACE_READ,
    PERMISSION.WORKSPACE_UPDATE,

    PERMISSION.MEMBER_INVITE,
    PERMISSION.MEMBER_REMOVE,
    PERMISSION.MEMBER_UPDATE_ROLE,

    PERMISSION.PROJECT_CREATE,
    PERMISSION.PROJECT_READ,
    PERMISSION.PROJECT_UPDATE,
    PERMISSION.PROJECT_DELETE,

    PERMISSION.TASK_CREATE,
    PERMISSION.TASK_READ,
    PERMISSION.TASK_UPDATE,
    PERMISSION.TASK_DELETE,
    PERMISSION.TASK_ASSIGN,
    PERMISSION.TASK_CHANGE_STATUS,
    PERMISSION.TASK_CHANGE_PRIORITY,
  ],

  [ROLE.MANAGER]: [
    PERMISSION.WORKSPACE_READ,

    PERMISSION.PROJECT_CREATE,
    PERMISSION.PROJECT_READ,
    PERMISSION.PROJECT_UPDATE,

    PERMISSION.TASK_CREATE,
    PERMISSION.TASK_READ,
    PERMISSION.TASK_UPDATE,
    PERMISSION.TASK_ASSIGN,
    PERMISSION.TASK_CHANGE_STATUS,
    PERMISSION.TASK_CHANGE_PRIORITY,
  ],

  [ROLE.MEMBER]: [
    PERMISSION.WORKSPACE_READ,

    PERMISSION.PROJECT_READ,

    PERMISSION.TASK_READ,
    PERMISSION.TASK_UPDATE,
    PERMISSION.TASK_CHANGE_STATUS,
  ],

  [ROLE.GUEST]: [
    PERMISSION.WORKSPACE_READ,
    PERMISSION.PROJECT_READ,
    PERMISSION.TASK_READ,
  ],
};