import type { ProjectRole } from "@/services/projectMember/types";

export const PROJECT_PERMISSION = {
  MEMBER_ADD: "project_member:add",
  MEMBER_READ: "project_member:read",
  MEMBER_UPDATE_ROLE: "project_member:update_role",
  MEMBER_REMOVE: "project_member:remove",

  TASK_CREATE: "task:create",
  TASK_READ: "task:read",
  TASK_UPDATE: "task:update",
  TASK_DELETE: "task:delete",
  TASK_ASSIGN: "task:assign",
  TASK_CHANGE_STATUS: "task:change_status",
  TASK_CHANGE_PRIORITY: "task:change_priority",

  COMMENT_CREATE: "comment:create", 
  COMMENT_UPDATE: "comment:update",
  COMMENT_DELETE: "comment:delete",

  ATTACHMENT_UPLOAD: "attachment:upload",
  ATTACHMENT_DELETE: "attachment:delete",

  ACTIVITY_READ: "activity:read",

  DOCUMENT_CREATE: "document:create",
  DOCUMENT_READ: "document:read",
  DOCUMENT_UPDATE: "document:update",
  DOCUMENT_DELETE: "document:delete",

  FILE_READ: "file:read",
  FILE_UPLOAD: "file:upload",
  FILE_DELETE: "file:delete",
} as const;

export type ProjectPermission =
  (typeof PROJECT_PERMISSION)[keyof typeof PROJECT_PERMISSION];

const PROJECT_ROLE_PERMISSIONS: Record<ProjectRole, ProjectPermission[]> = {
  PROJECT_ADMIN: [
    PROJECT_PERMISSION.MEMBER_ADD,
    PROJECT_PERMISSION.MEMBER_READ,
    PROJECT_PERMISSION.MEMBER_UPDATE_ROLE,
    PROJECT_PERMISSION.MEMBER_REMOVE,

    PROJECT_PERMISSION.TASK_CREATE,
    PROJECT_PERMISSION.TASK_READ,
    PROJECT_PERMISSION.TASK_UPDATE,
    PROJECT_PERMISSION.TASK_DELETE,
    PROJECT_PERMISSION.TASK_ASSIGN,
    PROJECT_PERMISSION.TASK_CHANGE_STATUS,
    PROJECT_PERMISSION.TASK_CHANGE_PRIORITY,

    PROJECT_PERMISSION.COMMENT_CREATE,
    PROJECT_PERMISSION.COMMENT_UPDATE,
    PROJECT_PERMISSION.COMMENT_DELETE,

    PROJECT_PERMISSION.ATTACHMENT_UPLOAD,
    PROJECT_PERMISSION.ATTACHMENT_DELETE,

    PROJECT_PERMISSION.ACTIVITY_READ,

    PROJECT_PERMISSION.DOCUMENT_CREATE,
    PROJECT_PERMISSION.DOCUMENT_READ,
    PROJECT_PERMISSION.DOCUMENT_UPDATE,
    PROJECT_PERMISSION.DOCUMENT_DELETE,

    PROJECT_PERMISSION.FILE_READ,
    PROJECT_PERMISSION.FILE_UPLOAD,
    PROJECT_PERMISSION.FILE_DELETE,
  ],

  PROJECT_MEMBER: [
    PROJECT_PERMISSION.MEMBER_READ,

    PROJECT_PERMISSION.TASK_CREATE,
    PROJECT_PERMISSION.TASK_READ,
    PROJECT_PERMISSION.TASK_UPDATE,
    PROJECT_PERMISSION.TASK_CHANGE_STATUS,
    PROJECT_PERMISSION.TASK_CHANGE_PRIORITY,

    PROJECT_PERMISSION.COMMENT_CREATE,
    PROJECT_PERMISSION.COMMENT_UPDATE,

    PROJECT_PERMISSION.ATTACHMENT_UPLOAD,

    PROJECT_PERMISSION.ACTIVITY_READ,

    PROJECT_PERMISSION.DOCUMENT_CREATE,
    PROJECT_PERMISSION.DOCUMENT_READ,
    PROJECT_PERMISSION.DOCUMENT_UPDATE,

    PROJECT_PERMISSION.FILE_READ,
    PROJECT_PERMISSION.FILE_UPLOAD,
  ],

  PROJECT_VIEWER: [
    PROJECT_PERMISSION.MEMBER_READ,

    PROJECT_PERMISSION.TASK_READ,

    PROJECT_PERMISSION.ACTIVITY_READ,

    PROJECT_PERMISSION.DOCUMENT_READ,

    PROJECT_PERMISSION.FILE_READ,
  ],
};

export const hasProjectPermission = (
  role: ProjectRole,
  permission: ProjectPermission,
): boolean => {
  return PROJECT_ROLE_PERMISSIONS[role].includes(permission);
};
